spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-meteo
          uri: lb://ms-meteo
          predicates:
            - Path=/api/meteo/**
        - id: ms-arrosage
          uri: lb://ms-arrosage
          predicates:
            - Path=/api/arrosage/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# Logging configuration
logging:
  level:
    com.example: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO
