spring:
  rabbitmq:
    enabled: true
    host: campbell.lmq.cloudamqp.com
    port: 5671
    username: tqiiuomc
    password: fTCuXSqEk4TX6wQ7dUeOvVo59XTwl98w
    virtual-host: tqiiuomc
    ssl:
      enabled: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/meteo_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
  scheduling:
    enabled: true
    thread-name-prefix: meteo-scheduler-

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# Irrigation messaging configuration
irrigation:
  exchange: irrigation.exchange
  routing-key: weather.key
  queue: arrosage.queue

# Scheduling and Open-Meteo configuration
app:
  scheduling:
    forecast:
      # Initial delay before first forecast generation (60 seconds)
      initial-delay: 60000
      # Interval between forecast generations (6 hours)
      fixed-delay: 21600000
  weather:
    provider: open-meteo
    base-url: https://api.open-meteo.com/v1/forecast
    forecast-days: 7
    hourly: temperature_2m,precipitation,wind_speed_10m
    timezone: auto

# Logging configuration
logging:
  level:
    com.example: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
